### ISSUE TITLE
using the library in windows platform

### ISSUE THREAD

**Issue by ImanHz** [sajari/docconv#106]
I am using the library in Linux without any problems. But when I compile the same code in Windows, the following error arises:

` error converting data: exec: "pdftotext": executable file not found in %PATH%`

Is there any way to install the dependencies in Windows?

I am using go version 1.17.

**Comment by ImanHz** [comment]
I was using the docd.exe wrongly. I wrote a code to run the docd.exe service automatically:
https://github.com/ImanHz/go-pdf2txt

**Comment by mish15** [comment]
ok excellent. Will close this. Glad you got it sorted.
