### ISSUE TITLE
go-charset/charset not more hosting in google code

### ISSUE THREAD

**Issue by avelino** [sajari/docconv#13]
new hosting: https://github.com/rogpeppe/go-charset

```
$ go get github.com/sajari/docconv
warning: code.google.com is shutting down; import path code.google.com/p/go-charset/charset will stop working
```

**Comment by mish15** [comment]
Thanks @avelino will fix up asap

**Comment by dhowden** [comment]
Presumably this is a the "semi-official" home for the new version? https://github.com/paulrosania/go-charset

**Comment by dhowden** [comment]
This is being included by another dependency: https://github.com/advancedlogic/GoOse/blob/master/crawler.go

**Comment by dhowden** [comment]
Will fork and send in a pull request.

**Comment by dhowden** [comment]
Fixed due to merge of https://github.com/advancedlogic/GoOse/pull/33.
