### ISSUE TITLE
support in images file

### ISSUE THREAD

**Issue by avelino** [sajari/docconv#14]
Image to text (used OCR), recommend `gosseract`[1]

[1] https://github.com/otiai10/gosseract

**Comment by dhowden** [comment]
Interesting idea!

We don't have a use case for this at the moment, so adding in the extra dep would complicate things unnecessarily (particularly as this would break `go get` building for docconv: would have to manually download the Tesseract-OCR code and get that building first if we were to use gosseract, or add build tags etc which is rather messy too).

Will leave this issue open as we could support this in the future should the need arise.

**Comment by avelino** [comment]
I'm with my team implementing this feature for our need on @poorny, we will send a PR, if you like the implementation we do merge. developed by @marioidival

**Comment by dhowden** [comment]
Closed via #17
