### ISSUE TITLE
ARM64 image

### ISSUE THREAD

**Issue by keribend** [sajari/docconv#142]
Hello there!

I've been using latest `docd` image with no issue at all, but recently I got the need of a different architecture.

Is it possible to publish images for ARM64? It seems that it hasn't been never done before:

* https://hub.docker.com/r/sajari/docd/tags

Thank you very much in advance

**Comment by eric-millin** [comment]
This, please

**Comment by KOSHI1108** [comment]
I want it too

**Comment by jonathaningram** [comment]
@keribend @eric-millin @KOSHI1108 does https://hub.docker.com/layers/sajari/docd/2.0.0-pre.3/images/sha256-ea1c61ebc78dc5e7d617f9f10084c8c7997f5b8fc655134a170192d6dc83d255?context=explore do the trick?

**Comment by jonathaningram** [comment]
Please open a new issue/PR if you experience issues.
