### ISSUE TITLE
Improve installation instructions for non-Go programmers

### ISSUE THREAD

**Issue by pjlsergeant** [sajari/docconv#24]
I know a little bit about computers. But I'm not a Go developer. Thus this:

> Compile the binary. Check the binary is executable and then launch as per above with relevant flag settings.

is not all that helpful to me. I have tried:

```
mkdir docconv
cd docconv
GOPATH=/Users/pjlsergeant/dev/docconv go get https://github.com/sajari/docconv/issues/new
cd github.com/sajari/docconv/
GOPATH=/Users/pjlsergeant/dev/docconv go install
```

And I don't appear to have generated any binaries (and no errors, either).

I'm sure I will be able to Google and solve this eventually, but I wonder if the two or three lines of magic invocation needed could be included under Installation Instructions?

**Comment by dhowden** [comment]
Thanks for the report.

I've updated the README in aba88e2e4916bbb3ae28212f7ae6c3366e36f289 to include more useful installation instructions.

Feel free to re-open this ticket if you need more info.

**Comment by pjlsergeant** [comment]
As far as I'm able to tell, my main issue was calling it the `docconv` executable, because it isn't - it's the `docd` executable, and I needed to `cd docd && go build docd` to make this work

**Comment by dhowden** [comment]
Sorry about that, fixed now.

Following the commands in the README should build the `docd` executable and place it in `GOPATH/bin` (which we assume is in your `PATH`).
