### ISSUE TITLE
Add govendor as dependency manager

### ISSUE THREAD

**Issue by gtsalles** [sajari/docconv#27]
What do you think about using [govendor](https://github.com/kardianos/govendor) as default dependency manager for the project?

Right now, the only external dependency existing is [justext](https://github.com/JalfResi/justext), but in #26 I've added a new dependency to deal with xlsx files, in the future, new dependencies may be added for dealing with new file types, and this could be a good approach for handling the dependency management.

**Comment by mish15** [comment]
We're likely to replace justext soon, so likely no external Go deps
