### ISSUE TITLE
Does this package support windows path?

### ISSUE THREAD

**Issue by lzmhhh123** [sajari/docconv#41]

**Comment by mish15** [comment]
I don't see why not. Don't use windows though. Did you try?

**Comment by lzmhhh123** [comment]
I tried, and got an error. Anyway, it works on linux.

**Comment by mish15** [comment]
@lzmhhh123 interesting. Can you provide any details, we can open that as a specific bug and see what we can do. Might be a simple fix.

**Comment by lzmhhh123** [comment]
@mish15 Please wait a period of time. I got these logs several days ago.

**Comment by mish15** [comment]
@lzmhhh123 ok no worries. Please report the stack trace as an issue when you get a chance
