### ISSUE TITLE
error converting data: exec: "pdftotext": executable file not found in $PATH

### ISSUE THREAD

**Issue by abraztsov** [sajari/docconv#46]
I'm trying to launch simple code from tutorial in this repo, only with my own PDF file and has this error `error converting data: exec: "pdftotext": executable file not found in $PATH`.

Platform MacOS. My PDF file is in `go/src/project` and in `go/bin`

My Go project file path: `/User/admin/go/src/project`

.bash_profile: 
```
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:/usr/local/go/bin
```

Code:

```
package main

import (
	"fmt"
	"log"

	"code.sajari.com/docconv"
)

func main() {
	res, err := docconv.ConvertPath("gsl-mit-edu-0to1.pdf")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(res)
}
```

What could be the problem ?

**Comment by mish15** [comment]
You need to install the dependencies. The readme has info on this, there’s several different ways to do this on OS X.

**Comment by abraztsov** [comment]
`sudo apt-get install` - is linux commands.

How to install brew, go, other methods ? Nothing about it in README

**Comment by mish15** [comment]
That is correct. We prefer to run in Linux and that is the example set of instructions. The libraries are available on brew, but may be much older and also would not match a deployed version in cloud or elsewhere. So you can either find the appropriate ones via brew, or use docker or Linux as per the readme.

**Comment by imnithin** [comment]
`brew install poppler` seems to work for me

**Comment by 4k1k0** [comment]
Same `poppler` should be included in the dependencies section for MacOS.
