### ISSUE TITLE
Split text by pages

### ISSUE THREAD

**Issue by abraztsov** [sajari/docconv#47]
Does it possible to split text by pages of the original document ?

Example:

text from docconv -> ```Page1/n/n1/n/nMy Name/n is Page2/n/n2/n/n...```
splited text -> ```["Page1", "My Name is Page2, "...",...]```

**Comment by mish15** [comment]
Currently no, but we’ve been planning a re-write to allow these types of things. The current code is a bit rigid.

**Comment by abraztsov** [comment]
Great, thanks!
