### ISSUE TITLE
docconv appears to be out of sync with latest github.com/otiai10/gosseract

### ISSUE THREAD

**Issue by PaulDuncanson** [sajari/docconv#48]
With current docconv at github/sajari/docconv that imports github.com/otiai10/gosseract/v1/gosseract the build on Mac OS terminal results in:
>go get -tags ocr code.sajari.com/docconv/...
package github.com/otiai10/gosseract/v1/gosseract: cannot find package "github.com/otiai10/gosseract/v1/gosseract" in any of:
	/usr/local/go/src/github.com/otiai10/gosseract/v1/gosseract (from $GOROOT)
	/Users/<YourMacUserID>/go/src/github.com/otiai10/gosseract/v1/gosseract (from $GOPATH)

Changing import to reference otiai10's current release (i.e. "github.com/otiai10/gosseract/v1/gosseract") in image_orc.go results in undefined references as follows:

>go get -tags ocr code.sajari.com/docconv/...
# code.sajari.com/docconv
/Users/<YourMacUserID>/go/src/code.sajari.com/docconv/image_ocr.go:35:11: undefined: gosseract.Must
/Users/<YourMacUserID>/go/src/code.sajari.com/docconv/image_ocr.go:35:26: undefined: gosseract.Params

**Comment by mish15** [comment]
Thanks @PaulDuncanson did you want to do a PR and fix this? I don't think we'll have time in the short term.

**Comment by DevelopAir** [comment]
You're welcome @mish15.  Will try.  Here's what I've discovered so far to help others.

It appears that docconv was developed against github.com/otiai10 version 2.0 that one can retrieve [here](https://github.com/otiai10/gosseract/releases/tag/v2.0).

Downloading and installing this version will resolve the previously reported issues.  When I get a chance I'll take a look at docconv to upgrade to the latest version of otiai10 and provide for review.  Looks like it'll just be a matter of refactoring the code to compensate for the missing gosseract.Must and gosseract.Params definitions.

**Comment by mish15** [comment]
ok great, yes that would be great. There's 99 commits since that version, so upgrading is likely the right thing to do. Let us know how you go!

**Comment by ayusdash** [comment]
Any update on this issue? We can use this package if it got resolved.

**Comment by mish15** [comment]
This will be resolved once https://github.com/sajari/docconv/pull/74 is merged
