### ISSUE TITLE
issues with deploying to gcloud

### ISSUE THREAD

**Issue by slav123** [sajari/docconv#63]
I tried to deploy it to appengine, and i'm failing. 

```

---------------------------------------------------------------------------------------------------------------- REMOTE BUILD OUTPUT -----------------------------------------------------------------------------------------------------------------
starting build "b30eafdb-e2e2-4a5d-b334-6be6535a8773"

FETCHSOURCE
Fetching storage object: gs://staging.xxx.appspot.com/us.gcr.io/xxx/appengine/docd.1:latest#1571314487109426
Copying gs://staging.xxx.appspot.com/us.gcr.io/xxx/appengine/docd.1:latest#1571314487109426...
/ [1 files][  6.4 MiB/  6.4 MiB]
Operation completed over 1 objects/6.4 MiB.
BUILD
Already have image (with digest): gcr.io/cloud-builders/docker
Sending build context to Docker daemon  13.49MB
Step 1/9 : FROM alpine
latest: Pulling from library/alpine
Digest: sha256:acd3ca9941a85e8ed16515bfc5328e4e2f8c128caa72959a58a127b7801ee01f
Status: Downloaded newer image for alpine:latest
 ---> 961769676411
Step 2/9 : MAINTAINER Hamish Ogilvy
 ---> Running in 1bf83502be90
Removing intermediate container 1bf83502be90
 ---> 1d609d316173
Step 3/9 : ENV CC=/usr/bin/gcc
 ---> Running in ebc84ab28e30
Removing intermediate container ebc84ab28e30
 ---> 857461fa7c94
Step 4/9 : ENV CXX=/usr/bin/g++
 ---> Running in 7022ffdf3aa6
Removing intermediate container 7022ffdf3aa6
 ---> e6a37cfd4e07
Step 5/9 : COPY dependencies/* /
COPY failed: no source files were specified
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.app.deploy) Cloud build failed. Check logs at https://console.cloud.google.com/gcr/builds/xxx?project=xxx Failure status: UNKNOWN: Error Response: [2] Build failed; check build logs for details
rm: appengine/dependencies: No such file or directory
```

**Comment by mish15** [comment]
@slav123 Are you running this with the `appengine.sh` script? This script adds a symlink to the dependencies so they should resolve ok.

**Comment by mish15** [comment]
Can you try this branch please? 
https://github.com/sajari/docconv/tree/appengine-63

Looks like the security settings have changed and prevent the symlink working. Also dependencies now have a clash, so there is a small change to the poppler version. Please test and ensure this is working ok

**Comment by benhinchley** [comment]
@mish15 This changes in this branch look to be okay, I've just deployed `docd` from that branch into our staging env.

**Comment by slav123** [comment]
Sorry for late replay - got something new instead:

`ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Legacy health checks are no longer supported for the App Engine Flexible environment. This app's feature setting is configured to use legacy health checks by default. For instructions on migrating to split health checks see https://cloud.google.com/appengine/docs/flexible/java/migrating-to-split-health-checks

rm: appengine/dependencies: No such file or directory`

**Comment by mish15** [comment]
That's strange as there aren't any health checks specified. This was deployable for us when the PR was created. Are you using a different app.yaml, e.g. https://github.com/sajari/docconv/blob/master/docd/appengine/app.yaml

These are easy to add, but I just want to make sure that is an issue first!

**Comment by slav123** [comment]
Default one:

    cat appengine/app.yaml
    runtime: custom 
    env: flex

    service: docd

    resources:
      memory_gb: .6

    manual_scaling:
      instances: 1

    handlers:
    - url: /.*
      script: _go_app%`

**Comment by mish15** [comment]
There are no health check settings in there. The error says `This app's feature setting is configured to use legacy health checks by default` so you probably have app settings causing this.

**Comment by slav123** [comment]
You are right. Just deployed to different project and went ok.
