### ISSUE TITLE
Use as internal go library

### ISSUE THREAD

**Issue by deranjer** [sajari/docconv#67]
Is there a way to use this as an interal/embedded library in a golang program?  I see that I can most likely achieve this with ODT and several other types since it returns a string.

However, with PDF it returns a BodyResult that is not exported and looks like it is interpreted directly by the command line?  Am I missing something?

**Comment by mish15** [comment]
You can use this directly embedded. Just note you need the dependencies running on that system to use them. 

See:
https://github.com/sajari/docconv#example-usage-code and https://godoc.org/code.sajari.com/docconv#ConvertPath

**Comment by deranjer** [comment]
Ah, so NO conversions can happen at all without those 3rd party apps installed?

**Comment by mish15** [comment]
Depends on the file extensions you need. We have some branches moving some of the file types into Go, but covering all document formats and versions is a pain, there are many, so it's not an immediate priority. You can run this either embedded or as a service where local embedding via a client is very simple also.

**Comment by deranjer** [comment]
Well I was hoping for as many as possible. I'm writing an EDMS and was hoping to scrape files for text (the ones that I can) and OCR the rest. The main formats would be PDF, doc, docx, odf. There are other libraries that do most of those formats but an all in one package would be very cool.
