### ISSUE TITLE
wvText: exec: "wvText": executable file not found in $PATH

### ISSUE THREAD

**Issue by wzhsh90** [sajari/docconv#79]
yum  install poppler-utils wv unrtf tidy all dependencies 

res, err := docconv.ConvertPath("/opt/test/测试.doc")

[root@izwz9594gzu20j2z7lneucz test]# ./main
2020/11/03 10:14:15 wvText: exec: "wvText": executable file not found in $PATH
2020/11/03 10:14:15 wvSummary: exec: "wvSummary": executable file not found in $PATH
2020/11/03 10:14:15 error converting data: error unzipping data: zip: not a valid zip file

**Comment by mish15** [comment]
If you can't run `wvSummary` or `wvText` on the command line, this package won't either. Please make sure they are in your path and executable.

**Comment by wzhsh90** [comment]
2020/11/03 11:02:46 wvText: exit status 255
2020/11/03 11:02:46 error converting data: error unzipping data: zip: not a valid zip file

**Comment by wzhsh90** [comment]
I convert the word export from 2007 to 2003 ,that is work right, but I convert the 2003 err

2020/11/03 11:02:46 wvText: exit status 255
2020/11/03 11:02:46 error converting data: error unzipping data: zip: not a valid zip file
