### ISSUE TITLE
wvText: exit status 255

### ISSUE THREAD

**Issue by wzhsh90** [sajari/docconv#80]
I convert the word export from 2007 to 2003 ,that is work right, but I convert the 2003 err

2020/11/03 11:02:46 wvText: exit status 255
2020/11/03 11:02:46 error converting data: error unzipping data: zip: not a valid zip file

**Comment by mish15** [comment]
This sounds like the file extension is possibly wrong for the file. Or it is corrupt. 

Possibly check if the file can be extracted using the cmd line tool first. If it can it may be the extension and you can a test with the failing document. If it can’t, then you’re probably out of luck anyway. 

Note: from memory the docx extension is a zip, doc is not etc.

**Comment by imclaren** [comment]
For what it’s worth I also sometimes get this error for random files that don’t have Microsoft file (.doc, .docx) extensions and are not .zip files

**Comment by jonathaningram** [comment]
@wzhsh90 I'm going to close this one out. If you come across a bug in docconv please feel free to create a new issue. Thanks 😊
