### ISSUE TITLE
do not need to specify a temporary file path

### ISSUE THREAD

**Issue by wangqianwei** [sajari/docconv#86]
![image](https://user-images.githubusercontent.com/11631575/113386257-715d3280-93bc-11eb-9119-00756d47cc4b.png)
I think do not need to specify a temporary file path, where win ,"/tmp" This path does not exist

**Comment by jonathaningram** [comment]
@wangqianwei can you please provide a bit more info? A minimal working example showing the issue you are having would help. Are you saying this is an issue on Windows?

**Comment by wangqianwei** [comment]
> @wangqianwei can you please provide a bit more info? A minimal working example showing the issue you are having would help. Are you saying this is an issue on Windows?

I developed and debugged on the Windows. But I found that you have solved the problem [commit](https://github.com/sajari/docconv/commit/d37fc7c11ecdf6212c159fe1a42b0adef1ee6e02).This should be my version problem

![image](https://user-images.githubusercontent.com/11631575/114361667-f6103380-9ba8-11eb-8f9a-cad43faa5ed1.png)

**Comment by jonathaningram** [comment]
@wangqianwei thank you for the info. I'll go ahead and close this. Please feel free to create a new issue if you come across any other bugs.
