### ISSUE TITLE
Fix temporary file creation

### ISSUE THREAD

**Issue by remLse** [sajari/docconv#87]
The following line throws an error message for me:
`f, err := ioutil.TempFile(os.TempDir(), "/docconv")`

error message:
`pattern contains path separator`

full error message thrown by `docconv.Convert()`:
`error converting data: error creating local file: error creating temporary file: pattern contains path separator`

This can be easily reproduced with go playground, just add and remove the slash to see the difference:
https://play.golang.org/p/VaCO9evqKzM

I suppose it could be fixed by just removing the slash, unless I'm missing the reason it needed to be there in the first place.

**Comment by jonathaningram** [comment]
@remLse sorry you are having issues!

What version of Go are you using?

I think that the path separator was added as an invalid pattern prefix: https://github.com/golang/go/commit/12cd55c062d6062a64076cb37f12ab7646df1be7

I need to check what version of Go it went out in and looks like we might need to patch docconv.

**Comment by jonathaningram** [comment]
@remLse looks like it might have gone out in go1.15:

```
% git tag --contains 12cd55c062d6062a64076cb37f12ab7646df1be7
go1.15
go1.15.1
go1.15.10
go1.15.11
go1.15.2
go1.15.3
go1.15.4
go1.15.5
go1.15.6
go1.15.7
go1.15.8
go1.15.9
go1.15beta1
go1.15rc1
go1.15rc2
go1.16
go1.16.1
go1.16.2
go1.16.3
go1.16beta1
go1.16rc1
```

**Comment by remLse** [comment]
I'm using go1.16.2

Thanks for looking at my issue!

**Comment by jonathaningram** [comment]
@remLse should be fixed in https://github.com/sajari/docconv/commit/70dbd5cc6965fba23b855f7e4901f2896ae06e98

You can upgrade to this using `go get code.sajari.com/docconv@70dbd5cc6965fba23b855f7e4901f2896ae06e98`. 

Let us know know you go if it resolves your issue.

**Comment by remLse** [comment]
That solves my issue, thanks a lot!
