### ISSUE TITLE
ConvertRTF ignores lines shorter than five characters

### ISSUE THREAD

**Issue by remLse** [sajari/docconv#90]
The issue seems to arise from rtf.go lines 31-33:
```
if len(line) > 4 && line[:4] != "### " {
	output += line + "\n"
}
```

**Comment by remLse** [comment]
I've prepared two files to reproduce the issue.

Output:
```
-----------------
12345
123456
```

but should be:
```
-----------------
1
12
123
1234
12345
123456
```

[test_files.zip](https://github.com/sajari/docconv/files/6286530/test_files.zip)

**Comment by jonathaningram** [comment]
Fixed in https://github.com/sajari/docconv/pull/91

Thank you @remLse for your contribution 👍🏻
