### ISSUE TITLE
Error occured while commond "go mod tidy"

### ISSUE THREAD

**Issue by Mmx233** [sajari/docconv#95]
```shell
go: finding module for package github.com/otiai10/gosseract/v1/gosseract
Crawler/module/crawler imports
        code.sajari.com/docconv imports
        github.com/otiai10/gosseract/v1/gosseract: module github.com/otiai10/gosseract@latest found (v2.2.1+incompatible), but does not contain package
github.com/otiai10/gosseract/v1/gosseract
```

**Comment by zolastro** [comment]
Just got the very same error

**Comment by zolastro** [comment]
It seems that the folder structure of [github.com/otiai10/gosseract](github.com/otiai10/gosseract) has changed and there is no longer a "v1/gosseract" folder. If you need to make it work, a workaround could be to go to your docconv library files at `$GOPATH/ pkg/mod/code.sajari.com/docconv@v1.1.0/` and modify the import at `image_ocr.go`.

 `"github.com/otiai10/gosseract/v1/gosseract"` →`"github.com/otiai10/gosseract"`

I'm going to propose this change as a pull request
